In [7]:
import os
import pandas as pd

csv_paths = os.listdir("../austin_raw")
AUSTIN_ID = '16000US4805000'

#tuple with percent and number
#convert prop to percent

In [8]:
from datausa_to_dict import csvs_to_dict

data = csvs_to_dict(csv_paths,AUSTIN_ID)

In [9]:
import json

with open('data.json','w') as f:
    json.dump(data,f,indent=4)

### County level csvs

In [10]:
def reduce(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(f"../austin_raw/{csv_path}")
    df = df[df['ID Geography'] == AUSTIN_ID]
    df = df.drop(columns=['ID Geography'])
    df = df[df['Year'] == df['Year'].max()]
    return df

In [7]:
csv_col_map = {
    'Citizenship':['Citizenship %'],
    'Race and Ethnicity':{
        'Race':'share'
    },
    'Applicants, Admissions &amp; Enrolled':['Admissions Enrolled', 'Admissions','Admitted who Enrolled','Applicant Admitted','Applicants'],
    'Property':{
        'Value Bucket':'share'
    },
    'Occupations':{
        'Occupation':'Share'
    },
    'Uninsured People':{
        'Kaiser Coverage':'share'
    },
    'Rent vs Own':['share'],
    'Employment by Industries':{
        'Industry':'Share'
    },
    'Household Income':{
        'Household Income Bucket':'share'
    }
}

In [ ]:
geo_data = {}
for csv in csv_paths:
    if csv.endswith('.csv') and csv[:-4] in csv_col_map:
        var_name = csv[:-4]
        df = reduce(csv)
        col_map = csv_col_map[var_name]
        geo_data[var_name] = {}
        if isinstance(col_map,list):
            for var in col_map:
                geo_data[var_name][var] = float(df[var].sum())
        else:
            for key_col,val_col in col_map.items():
                for key_col_group in df[key_col].unique():
                    try:
                        geo_data[var_name][key_col_group] = float(df[df[key_col] == key_col_group][val_col].sum())
                    except KeyError:
                        print(csv)

print(geo_data)

{'Applicants, Admissions &amp; Enrolled': {'Admissions Enrolled': 10103.0, 'Admissions': 26433.0, 'Admitted who Enrolled': 76.69261874545217, 'Applicant Admitted': 75.2863490460026, 'Applicants': 69490.0}, 'Property': {'Less Than $10,000': 0.0069195310663436, '$10,000 to $14,999': 0.0027034209262155, '$15,000 to $19,999': 0.000408834922679, '$20,000 to $24,999': 0.0023763529880722, '$25,000 to $29,999': 0.0017171066752522, '$30,000 to $34,999': 0.0022690338208689, '$35,000 to $39,999': 0.0013440448083075, '$40,000 to $49,999': 0.0034699864062388, '$50,000 to $59,999': 0.0018908615173908, '$60,000 to $69,999': 0.0014769161581782, '$70,000 to $79,999': 0.0017733214771205, '$80,000 to $89,999': 0.0021310520344647, '$90,000 to $99,999': 0.0008738846472265, '$100,000 to $124,999': 0.0077116487290344, '$125,000 to $149,999': 0.003827716963583, '$150,000 to $174,999': 0.0054017314158975, '$175,000 to $199,999': 0.0106654810453908, '$200,000 to $249,999': 0.0496223387401751, '$250,000 to $299,999': 0.0608346364946493, '$300,000 to $399,999': 0.1472623391490101, '$400,000 to $499,999': 0.1712047343084046, '$500,000 to $749,999': 0.2781866127004568, '$750,000 to $999,999': 0.1139371825141303, '$1,000,000 to $1,499,999': 0.073431862549699, '$1,500,000 to $1,999,999': 0.0206921575240957, '$2,000,000 or More': 0.0278672104171138}, 'Occupations': {'Management Occupations': 14.46065672897442, 'Business & Financial Operations Occupations': 8.79021303818212, 'Computer & Mathematical Occupations': 8.399190262113205, 'Architecture & Engineering Occupations': 3.518854448738509, 'Life, Physical, & Social Science Occupations': 1.464714181805435, 'Community & Social Service Occupations': 1.5111601861345532, 'Legal Occupations': 2.113205563004443, 'Education Instruction, & Library Occupations': 6.32173935904514, 'Arts, Design, Entertainment, Sports, & Media Occupations': 4.286352761784578, 'Health Diagnosing & Treating Practitioners & Other Technical Occupations': 3.54023713752399, 'Health Technologists & Technicians': 1.2284529975199587, 'Healthcare Support Occupations': 1.713419389892298, 'Food Preparation & Serving Related Occupations': 5.366704349273952, 'Building & Grounds Cleaning & Maintenance Occupations': 2.7480260448160125, 'Personal Care & Service Occupations': 2.4211513351035396, 'Fire Fighting & Prevention, & Other Protective Service Workers Including Supervisors': 0.6891535434795943, 'Law Enforcement Workers Including Supervisors': 0.3202145279596182, 'Sales & Related Occupations': 9.676543015134389, 'Office & Administrative Support Occupations': 8.868207271866867, 'Farming, Fishing, & Forestry Occupations': 0.0932425445399654, 'Construction & Extraction Occupations': 3.992253157013785, 'Installation, Maintenance, & Repair Occupations': 1.5402546643180763, 'Production Occupations': 2.5485711281121013, 'Transportation Occupations': 2.408707311302153}, 'Uninsured People': {'Medicaid': 9.369953568899032, 'Medicare': 6.82983132656541, 'Employer': 58.19868314052622, 'OtherPublic': 0.6900133784528213, 'NonGroup': 12.108496629154535, 'Uninsured': 12.803021956401984}, 'Citizenship': {'Citizenship %': 0.8847487273038461}, 'Race and Ethnicity': {'White Alone': 0.6322487325219525, 'Black or African American Alone': 0.078722440570986, 'American Indian & Alaska Native Alone': 0.0078908205159245, 'Asian Alone': 0.0837453898029851, 'Native Hawaiian & Other Pacific Islander Alone': 0.000498850972968, 'Some Other Race Alone': 0.08220187392637461, 'Two or More Races': 0.1146918916888088}, 'Household Income': {'< $10,000': 0.0516475646392281, '$10,000-$14,999': 0.0281649526447779, '$15,000-$19,999': 0.0229295238005195, '$20,000-$24,999': 0.0263071435831133, '$25,000-$29,999': 0.0287794950824786, '$30,000-$34,999': 0.0272478662377475, '$35,000-$39,999': 0.0290513119299232, '$40,000-$44,999': 0.0313156644503745, '$45,000-$49,999': 0.0334098359880778, '$50,000-$59,999': 0.0717620113501261, '$60,000-$74,999': 0.0894041065616587, '$75,000-$99,999': 0.1259930178524578, '$100,000-$124,999': 0.0961073463821177, '$125,000-$149,999': 0.0766547146041283, '$150,000-$199,999': 0.103574037000182, '$200,000+': 0.1576514078930885}, 'Rent vs Own': {'share': 0.4444300000709087}, 'Employment by Industries': {'Agriculture, Forestry, Fishing & Hunting': 0.1642260605901271, 'Mining, Quarrying, & Oil & Gas Extraction': 0.3887442928376756, 'Construction': 5.951748735879977, 'Manufacturing': 6.94166206588322, 'Wholesale Trade': 1.7849287097650532, 'Retail Trade': 9.377535908019384, 'Transportation & Warehousing': 3.1192435435672285, 'Utilities': 0.582415367493055, 'Information': 3.778601537099841, 'Finance & Insurance': 4.635486499986855, 'Real Estate & Rental & Leasing': 2.5683764054298006, 'Professional, Scientific, & Technical Services': 17.540464985847116, 'Management of Companies & Enterprises': 0.1354821182883333, 'Administrative & Support & Waste Management Services': 4.251649709493388, 'Educational Services': 9.811148793718395, 'Health Care & Social Assistance': 9.56419626504018, 'Arts, Entertainment, & Recreation': 2.2287071360342123, 'Accommodation & Food Services': 7.253113196799607, 'Other Services, Except Public Administration': 4.562925572468912, 'Public Administration': 5.35934309575764}}

In [7]:
geo_data

{'Applicants, Admissions &amp; Enrolled': {'Admissions Enrolled': 10103.0,
  'Admissions': 26433.0,
  'Admitted who Enrolled': 76.69261874545217,
  'Applicant Admitted': 75.2863490460026,
  'Applicants': 69490.0},
 'Property': {'Less Than $10,000': 0.0069195310663436,
  '$10,000 to $14,999': 0.0027034209262155,
  '$15,000 to $19,999': 0.000408834922679,
  '$20,000 to $24,999': 0.0023763529880722,
  '$25,000 to $29,999': 0.0017171066752522,
  '$30,000 to $34,999': 0.0022690338208689,
  '$35,000 to $39,999': 0.0013440448083075,
  '$40,000 to $49,999': 0.0034699864062388,
  '$50,000 to $59,999': 0.0018908615173908,
  '$60,000 to $69,999': 0.0014769161581782,
  '$70,000 to $79,999': 0.0017733214771205,
  '$80,000 to $89,999': 0.0021310520344647,
  '$90,000 to $99,999': 0.0008738846472265,
  '$100,000 to $124,999': 0.0077116487290344,
  '$125,000 to $149,999': 0.003827716963583,
  '$150,000 to $174,999': 0.0054017314158975,
  '$175,000 to $199,999': 0.0106654810453908,
  '$200,000 to $249,999': 0.0496223387401751,
  '$250,000 to $299,999': 0.0608346364946493,
  '$300,000 to $399,999': 0.1472623391490101,
  '$400,000 to $499,999': 0.1712047343084046,
  '$500,000 to $749,999': 0.2781866127004568,
  '$750,000 to $999,999': 0.1139371825141303,
  '$1,000,000 to $1,499,999': 0.073431862549699,
  '$1,500,000 to $1,999,999': 0.0206921575240957,
  '$2,000,000 or More': 0.0278672104171138},
 'Occupations': {'Management Occupations': 14.46065672897442,
  'Business & Financial Operations Occupations': 8.79021303818212,
  'Computer & Mathematical Occupations': 8.399190262113205,
  'Architecture & Engineering Occupations': 3.518854448738509,
  'Life, Physical, & Social Science Occupations': 1.464714181805435,
  'Community & Social Service Occupations': 1.5111601861345532,
  'Legal Occupations': 2.113205563004443,
  'Education Instruction, & Library Occupations': 6.32173935904514,
  'Arts, Design, Entertainment, Sports, & Media Occupations': 4.286352761784578,
  'Health Diagnosing & Treating Practitioners & Other Technical Occupations': 3.54023713752399,
  'Health Technologists & Technicians': 1.2284529975199587,
  'Healthcare Support Occupations': 1.713419389892298,
  'Food Preparation & Serving Related Occupations': 5.366704349273952,
  'Building & Grounds Cleaning & Maintenance Occupations': 2.7480260448160125,
  'Personal Care & Service Occupations': 2.4211513351035396,
  'Fire Fighting & Prevention, & Other Protective Service Workers Including Supervisors': 0.6891535434795943,
  'Law Enforcement Workers Including Supervisors': 0.3202145279596182,
  'Sales & Related Occupations': 9.676543015134389,
  'Office & Administrative Support Occupations': 8.868207271866867,
  'Farming, Fishing, & Forestry Occupations': 0.0932425445399654,
  'Construction & Extraction Occupations': 3.992253157013785,
  'Installation, Maintenance, & Repair Occupations': 1.5402546643180763,
  'Production Occupations': 2.5485711281121013,
  'Transportation Occupations': 2.408707311302153},
 'Uninsured People': {'Medicaid': 9.369953568899032,
  'Medicare': 6.82983132656541,
  'Employer': 58.19868314052622,
  'OtherPublic': 0.6900133784528213,
  'NonGroup': 12.108496629154535,
  'Uninsured': 12.803021956401984},
 'Citizenship': {'Citizenship %': 0.8847487273038461},
 'Race and Ethnicity': {'White Alone': 0.6322487325219525,
  'Black or African American Alone': 0.078722440570986,
  'American Indian & Alaska Native Alone': 0.0078908205159245,
  'Asian Alone': 0.0837453898029851,
  'Native Hawaiian & Other Pacific Islander Alone': 0.000498850972968,
  'Some Other Race Alone': 0.08220187392637461,
  'Two or More Races': 0.1146918916888088},
 'Household Income': {'< $10,000': 0.0516475646392281,
  '$10,000-$14,999': 0.0281649526447779,
  '$15,000-$19,999': 0.0229295238005195,
  '$20,000-$24,999': 0.0263071435831133,
  '$25,000-$29,999': 0.0287794950824786,
  '$30,000-$34,999': 0.0272478662377475,
  '$35,000-$39,999': 0.0290513119299232,
  '$40,000-$44,999': 0.0313156644503745,
  '$45,000-$49,999': 0.0334098359880778,
  '$50,000-$59,999': 0.0717620113501261,
  '$60,000-$74,999': 0.0894041065616587,
  '$75,000-$99,999': 0.1259930178524578,
  '$100,000-$124,999': 0.0961073463821177,
  '$125,000-$149,999': 0.0766547146041283,
  '$150,000-$199,999': 0.103574037000182,
  '$200,000+': 0.1576514078930885},
 'Rent vs Own': {'share': 0.4444300000709087},
 'Employment by Industries': {'Agriculture, Forestry, Fishing & Hunting': 0.1642260605901271,
  'Mining, Quarrying, & Oil & Gas Extraction': 0.3887442928376756,
  'Construction': 5.951748735879977,
  'Manufacturing': 6.94166206588322,
  'Wholesale Trade': 1.7849287097650532,
  'Retail Trade': 9.377535908019384,
  'Transportation & Warehousing': 3.1192435435672285,
  'Utilities': 0.582415367493055,
  'Information': 3.778601537099841,
  'Finance & Insurance': 4.635486499986855,
  'Real Estate & Rental & Leasing': 2.5683764054298006,
  'Professional, Scientific, & Technical Services': 17.540464985847116,
  'Management of Companies & Enterprises': 0.1354821182883333,
  'Administrative & Support & Waste Management Services': 4.251649709493388,
  'Educational Services': 9.811148793718395,
  'Health Care & Social Assistance': 9.56419626504018,
  'Arts, Entertainment, & Recreation': 2.2287071360342123,
  'Accommodation & Food Services': 7.253113196799607,
  'Other Services, Except Public Administration': 4.562925572468912,
  'Public Administration': 5.35934309575764}}

In [9]:
df = reduce('Citizenship.csv')
#df = df.drop(columns=['ID Group', 'Group', 'ID Subgroup', 'Subgroup', 'ID Occupation','ID Year', 'Year', 'ID State', 'State', 'Geography', 'Slug Geography'])
df.head()

,ID Citizenship,Citizenship,ID Year,Year,Citizenship Status,Geography,Slug Geography,Citizenship %
4,0,Citizen,2022,2022,847768,"Austin, TX",austin-tx,0.884749

In [3]:
csv_paths

['Applicants, Admissions &amp; Enrolled.csv',
 '.DS_Store',
 'Property.csv',
 'Occupations.csv',
 'Uninsured People.csv',
 'Citizenship.csv',
 'Race and Ethnicity.csv',
 'Household Income.csv',
 'Rent vs Own.csv',
 'Poverty &amp; Diversity.csv',
 'Employment by Industries.csv']

In [3]:
citizenship = pd.read_csv("../austin_raw/Citizenship.csv")
citizenship.head()

,ID Citizenship,Citizenship,ID Year,Year,Citizenship Status,Geography,ID Geography,Slug Geography,Citizenship %
0,0,Citizen,2022,2022,309482689,United States,01000US,united-states,0.934717
1,0,Citizen,2022,2022,26293082,Texas,04000US48,texas,0.899113
2,0,Citizen,2022,2022,1151767,"Travis County, TX",05000US48453,travis-county-tx,0.893498
3,0,Citizen,2022,2022,570765,"Williamson County, TX",05000US48491,williamson-county-tx,0.924471
4,0,Citizen,2022,2022,847768,"Austin, TX",16000US4805000,austin-tx,0.884749

In [9]:
fbp = reduce("Race and Ethnicity.csv")
citizenship = reduce("Citizenship.csv")

In [11]:
fbp

,ID Race,Race,ID Ethnicity,Ethnicity,ID Year,Year,Hispanic Population Moe,Geography,Slug Geography,Population,share
0,0,White Alone,0,Not Hispanic or Latino,2022,2022,3991.000000,"Austin, TX",austin-tx,456627,0.476546
1,0,White Alone,1,Hispanic or Latino,2022,2022,4610.000000,"Austin, TX",austin-tx,149195,0.155703
2,1,Black or African American Alone,0,Not Hispanic or Latino,2022,2022,2949.000000,"Austin, TX",austin-tx,71592,0.074715
3,1,Black or African American Alone,1,Hispanic or Latino,2022,2022,817.000000,"Austin, TX",austin-tx,3840,0.004008
4,2,American Indian & Alaska Native Alone,0,Not Hispanic or Latino,2022,2022,279.000000,"Austin, TX",austin-tx,1168,0.001219
5,2,American Indian & Alaska Native Alone,1,Hispanic or Latino,2022,2022,1506.000000,"Austin, TX",austin-tx,6393,0.006672
6,3,Asian Alone,0,Not Hispanic or Latino,2022,2022,2576.000000,"Austin, TX",austin-tx,79178,0.082632
7,3,Asian Alone,1,Hispanic or Latino,2022,2022,326.000000,"Austin, TX",austin-tx,1067,0.001114
8,4,Native Hawaiian & Other Pacific Islander Alone,0,Not Hispanic or Latino,2022,2022,122.000000,"Austin, TX",austin-tx,375,0.000391
9,4,Native Hawaiian & Other Pacific Islander Alone,1,Hispanic or Latino,2022,2022,113.000000,"Austin, TX",austin-tx,103,0.000107
10,5,Some Other Race Alone,0,Not Hispanic or Latino,2022,2022,700.000000,"Austin, TX",austin-tx,3292,0.003436
11,5,Some Other Race Alone,1,Hispanic or Latino,2022,2022,5234.000000,"Austin, TX",austin-tx,75474,0.078766
12,6,Two or More Races,0,Not Hispanic or Latino,2022,2022,2019.194146,"Austin, TX",austin-tx,34086,0.035573
13,6,Two or More Races,1,Hispanic or Latino,2022,2022,4318.773205,"Austin, TX",austin-tx,75812,0.079119

In [8]:
citizenship.head()

,ID Citizenship,Citizenship,ID Year,Year,Citizenship Status,Geography,ID Geography,Slug Geography,Citizenship %
2,0,Citizen,2022,2022,90210,"Bastrop County, TX",05000US48021,bastrop-county-tx,0.916442
5,0,Citizen,2022,2022,42250,"Caldwell County, TX",05000US48055,caldwell-county-tx,0.915672
6,0,Citizen,2022,2022,232001,"Hays County, TX",05000US48209,hays-county-tx,0.945588
7,0,Citizen,2022,2022,1151767,"Travis County, TX",05000US48453,travis-county-tx,0.893498
8,0,Citizen,2022,2022,570765,"Williamson County, TX",05000US48491,williamson-county-tx,0.924471

In [9]:
pc_ratio.head()

,ID Year,Year,Patient to Primary Care Physician Ratio,Patient to Primary Care Physician Ratio Data Source Years,Geography,ID Geography,Slug Geography
0,2023,2023,3817,2020,"Bastrop County, TX",05000US48021,bastrop-county-tx
5,2023,2023,1170,2020,"Travis County, TX",05000US48453,travis-county-tx
6,2023,2023,1471,2020,"Williamson County, TX",05000US48491,williamson-county-tx

#### Race and Ethnicity

In [ ]:
diversity = reduce("../county_raw/Race and Ethnicity.csv")
diversity.head()

,ID Race,Race,ID Ethnicity,Ethnicity,ID Year,Year,Hispanic Population Moe,Geography,ID Geography,Slug Geography,Population,share
0,0,White Alone,0,Not Hispanic or Latino,2022,2022,1390.0,"Travis County, TX",05000US48453,travis-county-tx,614956,0.477060
1,0,White Alone,1,Hispanic or Latino,2022,2022,7196.0,"Travis County, TX",05000US48453,travis-county-tx,198873,0.154278
2,1,Black or African American Alone,0,Not Hispanic or Latino,2022,2022,1711.0,"Travis County, TX",05000US48453,travis-county-tx,102001,0.079129
3,1,Black or African American Alone,1,Hispanic or Latino,2022,2022,1048.0,"Travis County, TX",05000US48453,travis-county-tx,5054,0.003921
4,2,American Indian & Alaska Native Alone,0,Not Hispanic or Latino,2022,2022,349.0,"Travis County, TX",05000US48453,travis-county-tx,1582,0.001227

In [13]:
diversity.to_dict(orient='records')

[{'ID Race': 0,
  'Race': 'White Alone',
  'ID Ethnicity': 0,
  'Ethnicity': 'Not Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 1390.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 614956,
  'share': 0.4770599214617851},
 {'ID Race': 0,
  'Race': 'White Alone',
  'ID Ethnicity': 1,
  'Ethnicity': 'Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 7196.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 198873,
  'share': 0.1542782536650908},
 {'ID Race': 1,
  'Race': 'Black or African American Alone',
  'ID Ethnicity': 0,
  'Ethnicity': 'Not Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 1711.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 102001,
  'share': 0.079128570253845},
 {'ID Race': 1,
  'Race': 'Black or African American Alone',
  'ID Ethnicity': 1,
  'Ethnicity': 'Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 1048.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 5054,
  'share': 0.0039207046407675},
 {'ID Race': 2,
  'Race': 'American Indian & Alaska Native Alone',
  'ID Ethnicity': 0,
  'Ethnicity': 'Not Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 349.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 1582,
  'share': 0.0012272565773039},
 {'ID Race': 2,
  'Race': 'American Indian & Alaska Native Alone',
  'ID Ethnicity': 1,
  'Ethnicity': 'Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 1733.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 8405,
  'share': 0.0065202854186093},
 {'ID Race': 3,
  'Race': 'Asian Alone',
  'ID Ethnicity': 0,
  'Ethnicity': 'Not Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 1675.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 91043,
  'share': 0.0706277626848836},
 {'ID Race': 3,
  'Race': 'Asian Alone',
  'ID Ethnicity': 1,
  'Ethnicity': 'Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 725.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 1837,
  'share': 0.0014250760635318},
 {'ID Race': 4,
  'Race': 'Native Hawaiian & Other Pacific Islander Alone',
  'ID Ethnicity': 0,
  'Ethnicity': 'Not Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 136.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 504,
  'share': 0.0003909843963092},
 {'ID Race': 4,
  'Race': 'Native Hawaiian & Other Pacific Islander Alone',
  'ID Ethnicity': 1,
  'Ethnicity': 'Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 100.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 131,
  'share': 0.0001016249125327},
 {'ID Race': 5,
  'Race': 'Some Other Race Alone',
  'ID Ethnicity': 0,
  'Ethnicity': 'Not Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 936.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 4691,
  'share': 0.0036391027839019},
 {'ID Race': 5,
  'Race': 'Some Other Race Alone',
  'ID Ethnicity': 1,
  'Ethnicity': 'Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 6134.0,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 107064,
  'share': 0.0830562567588324},
 {'ID Race': 6,
  'Race': 'Two or More Races',
  'ID Ethnicity': 0,
  'Ethnicity': 'Not Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 2640.9068518219265,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 44696,
  'share': 0.0346734892409472},
 {'ID Race': 6,
  'Race': 'Two or More Races',
  'ID Ethnicity': 1,
  'Ethnicity': 'Hispanic or Latino',
  'ID Year': 2022,
  'Year': 2022,
  'Hispanic Population Moe': 5594.873099543903,
  'Geography': 'Travis County, TX',
  'ID Geography': '05000US48453',
  'Slug Geography': 'travis-county-tx',
  'Population': 108217,
  'share': 0.0839507111416589}]